site_name: seatest
site_description: "seatest: a featherweight cross-platform C17 test framework for C applications."
site_author: Ryan M. Lederman
site_url: https://seatest.rml.dev
repo_url: https://github.com/aremmell/seatest
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs
      - navigation.sections
      - navigation.expand
      - navigation.indexes
      - navigation.footer
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  font:
    code: Source Code Pro
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Troubleshooting: troubleshooting.md
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: Copyright &copy; 2023 Ryan M. Lederman
